### ISSUE TITLE
Use intendation style of the file

### ISSUE THREAD

**Issue by laeubi** [eclipse/lemminx-maven#340]
1. I have a pom file that uses spaces for indentation
2. I select a block of xml and hit `tab`
3. now I might end with a mixed style using tab and spaces for indentation

Of course the other way round can happen as well... `lemminx-maven` should always use the style found in the file similar to what IntelliJ do with the "automatic" setting: https://www.jetbrains.com/help/idea/indentation.html#detect-indentation

> You can configure IntelliJ IDEA to detect the indentation style in the current file and use this style instead of the indents specified in the code style settings for a specific language.

**Comment by mickaelistria** [comment]
I don't think LemMinX-Maven in involved here, nor that the problem is even specific to pom files, or even for XML files.
How to process a tab in the generic editor is actually configured in Preferences > General > Editors > Text Editors. The problem is most likely the same in every text editor that doesn't provide an overriding way to override tab-handling. The problem here would better be reprorted to Platform Text I believe.
