### ISSUE TITLE
Issue warning when dependency is added twice

### ISSUE THREAD

**Issue by mickaelistria** [eclipse/lemminx-maven#40]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=562666

**Comment by pauldpong** [comment]
Has this been fixed? I am testing using the same dependencies from the bugzilla. 

![image](https://user-images.githubusercontent.com/29359765/89063419-2d4df580-d336-11ea-8271-0f5e332a8244.png)

**Comment by AObuchow** [comment]
@pauldpong I guess the Maven Builder already detects that a duplicate dependency exists. An improvement we could make would be to create a range for this kind of warning that spans the duplicate `<dependency>...</dependency>`. This would make it more obvious that there's an issue (rather than having to notice the warning icon next to the line numbers).

However.. I'm not really sure if this is worth the time/effort, @mickaelistria what are your thoughts?

**Comment by mickaelistria** [comment]
Looks good to me then. Thanks for testing!
