### ISSUE TITLE
[Question] Steps to build m2e master with the latest builds from lemminx-maven

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#43]
if I locally install the lemminx-maven and try to build m2e master will that package and create an update site with the latest changes of lemminx-maven which I locally installed?

if not how to get a fresh update site of m2e with changes from a branch on limminx-maven that one is experimenting on ?

**Comment by gayanper** [comment]
Also I would like to know if the following workflow works.
1. Workspace with both m2e and lemminx-maven.
2. Run m2e as an Eclipse application with the Launcher VM Argument set `-Dorg.eclipse.wildwebdeveloper.xml.internal.XMLLanguageServer.debugPort=10003`
3. Run a remote debug session on port 10003 after a pom.xml file is loaded in the eclipse instance which started in step 2.

When I run step3 I'm unable to connect to the language server.

**Comment by AObuchow** [comment]
@gayanper I'll let @mickaelistria respond with regards to using a new build of lemminx-maven inside m2e locally.

However, one thing that might help you in debuging is using the LSP4E launch, detailed [here](https://github.com/AObuchow/lsp4xml-extensions-maven/tree/Add_submodule_completion#lsp4e--launch). Just thought I'd mention it as this is how I initially started testing & developping lemminx-maven.
Nowdays I just write tests (which can lead to some UX problems going unnoticed, but they get caught by users like yourself :) )

**Comment by mickaelistria** [comment]
This is more a question for m2e.
But `mvn install` to install maven-lemminx then `mvn verify` on m2e-core does a nice part of the job for testing *from the IDE*.
Unfortunately, it's currently a bit more complex for the Tycho build because of Git-based qualifiers and baseline replacement replacing the newly built bundle (which contains local lemminx-maven jar) by the baseline one because they have the exact same version. To avoid this replacement and get the latest lemminx-maven cascading to a newer org.eclipse.m2e.editor.lemminx bundle and so on, you need to make an extra commit somewhere under the `org.eclipse.m2e.editor.lemminx` bundle. In Eclipse Platform, there is usually a file named `forceQualifierUpdate.txt` that's committed and updated whenever we want to enforce usage of local build vs baseline.

**Comment by mickaelistria** [comment]
covered by https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.editor.lemminx/HOWTO-DEV.md
