### ISSUE TITLE
Doesn't support properties defined in `.mvn/maven.config`

### ISSUE THREAD

**Issue by segevfiner** [eclipse/lemminx-maven#549]
To create a new structured build/pomless Tycho build for an Eclipse plugin, I have been instructed to look at https://tycho.eclipseprojects.io/doc/4.0.5/StructuredBuild.html, but it seems `.mvn/maven.config` that I'm instructed to create for this is not being picked up by this plugin and as such I get:
```
'build.plugins.plugin.version' for org.eclipse.tycho:target-platform-configuration must be a valid version but is '${tycho-version}'.
```
When opening the pom.xml in Eclipse.

See also https://github.com/eclipse-tycho/tycho/discussions/3481#discussioncomment-8453079

**Comment by laeubi** [comment]
I also noticed this today, this is quite annoying, any hints where properties are evaluated so one can probably suggest a fix?

**Comment by mickaelistria** [comment]
Best is to have a look at Maven code and look for how `maven.config` file is loaded in the session.

**Comment by laeubi** [comment]
> Best is to have a look at Maven code and look for how `maven.config` file is loaded in the session.

Well this happens as part of MavenCLI, m2e already supports it I just don't know how this could / should be applied to lemminx, e.g you can look at

https://github.com/eclipse-m2e/m2e-core/blob/6f195b7171868d6c5d77a16c1aa7c34bdfbb55c7/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/embedder/MavenProperties.java#L278-L288

it extracts the data from the maven config given the Multi Module Directory is known like here:

https://github.com/eclipse-m2e/m2e-core/blob/6f195b7171868d6c5d77a16c1aa7c34bdfbb55c7/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/embedder/MavenProperties.java#L222-L236

it would be great if this could be fixed because currently users blame this on m2e even though it actually supports this and it is a language server error...

**Comment by mickaelistria** [comment]
Just to not set false expectation: neither Victor nor I are very active on this project at the moment, so it's not likely we try to fix it soon. But as usual, we try to make reviews of incoming PRs highest priority ;)

**Comment by laeubi** [comment]
Wel my problem is that I'm not very familiar with the codebase, but you knwo m2e as well, so maybe you can point me to where something similar like the `MavenExecutionRequest` building happens in lemminx I probably can give it a try :-D

**Comment by HannesWell** [comment]
I also looked a bit into this a while ago and I assumed one could start in [m2e's InitializationOptionsProvider](https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.editor.lemminx/src/org/eclipse/m2e/editor/lemminx/InitializationOptionsProvider.java) to feed the language server with the corresponding properties.
Of course changes and different roots have to be considered. But I'm not sure this is really the right place or if something is missing.

**Comment by laeubi** [comment]
This one seems only called once and on config change but not for pom files I open with the editor, as each `pom.xml` can have different settings this seems not the right location to hook into.

**Comment by laeubi** [comment]
@mickaelistria I started a very basic implementation here:
- https://github.com/eclipse/lemminx-maven/pull/552

I have not tested this yet but found already some uncertainties, I added `TODO` in the code so maybe a lemminx contributor can help here.
