### ISSUE TITLE
Add support for dependency (validation, completion) on workspace projects

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#77]
- Create a new module ModuleA in workspace
- Create another module ModuleB in the same workspace
- Now try to add a dependency in the ModuleB pom file to ModuleA, The dependency is not part of the completion list.

**Comment by AObuchow** [comment]
There might be some useful code in `org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(RepositorySystemSession, ArtifactDescriptorRequest, ArtifactDescriptorResult)` for this.

**Comment by AObuchow** [comment]
Might be relevant:
- https://maven.apache.org/components/resolver-archives/resolver-LATEST/apidocs/org/eclipse/aether/DefaultRepositorySystemSession.html#setWorkspaceReader-org.eclipse.aether.repository.WorkspaceReader-
- https://maven.apache.org/components/resolver-archives/resolver-LATEST/apidocs/org/eclipse/aether/repository/WorkspaceReader.html

**Comment by mickaelistria** [comment]
Adding validation to the scope of this bug. Eg create a parent pom that's not in a remote repo; reference it in another pom (without project.relativePath), then LemMinX-Maven doesn't resolve the parent to the other known pom.

**Comment by mickaelistria** [comment]
This should now be fixed with merged patches.

We'll most likely face same performance issues as m2e on https://bugs.eclipse.org/bugs/show_bug.cgi?id=515668 with LemMinX-Maven about multiple project hierarchies stroed in memory, and the same approach (grouping project builds) will probably need to be used.
It won't be an easy task, it may actually a bit simpler for LemMinX-Maven than for m2e because things are better isolated than in m2e. However, we may also need to implement the "Facade" approach of m2e to simply avoid loading project; that would be a bigger piece of work!
But this is not currently highest priority for LemMinX-Maven.
